kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "kv/data/test"
type: Opaque
data:
  password: <path:secret/data/test-secret#foo>  # From the key password-vault-key in Vault
