apiVersion: v1
kind: Namespace
metadata:
  name: test-ng2
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: test
  namespace: test-ng2
spec:
  containers:
  - image: ubuntu
    env:
    - name: TEST_VALUE
      value: test
    name: test
    command: ["sleep", "inf"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
