apiVersion: v1
kind: Pod
metadata:
  labels:
    run: ubuntu
  name: {{ .Values.name1 }}
spec:
  containers:
  - image: ubuntu
    env:
    - name: DEMO_GREETING
      value: {{ .Values.testvalue }}
    name: {{ .Values.name1 }}
    command: ["sleep", "inf"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
