apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu
  labels:
    run: ubuntu
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      run: ubuntu
  template:
    metadata:
      labels:
        run: ubuntu
    spec:
      containers:
      - image: ubuntu
        env:
        - name: TEST_VALUE
          value: {{ .Values.testvalue }}
        name: {{ .Values.name }}
        command: ["sleep", "inf"]
        resources: {}
